### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by radekdob** [mapbox/mapbox-gl-draw#1019]
Hello,

**mapbox-gl-js version**: 1.12
**mapbox-gl-draw version**: 1.2.0

### Steps to Trigger Behavior

 1. Add Mapbox Draw control to mapbox map.
 2. Open in browser and switch to touch device.
 3. Click on map and check console 

Just open official web and switch to device toolbar in developer console. Touch a map and check console.
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

### Expected Behavior
Should not generate that issue. If any mapbox layers was added, they are not reacting to click/touch event. Only drawing tools and features which was drawed are "alive".
### Actual Behavior
After clicking on map when mapbox draw was added as control, mapbox draw generates error.  
Error text : 
" Unable to preventDefault inside passive event listener invocation."

**Comment by radekdob** [comment]
Ok, I guess this error "Unable to preventDefault inside passive event listener invocation." is not bad behaviour.
The issue is that when I was using only pure mapbox, it reacted on "click" event both on touch devices and mouse. 
When I added Mapbox draw, event from mapbox mouse click started listening only on mouse click, not as previously on touch too.

Maybe it will help somebody in the furure :)

**Comment by petrovnn** [comment]
@radekdob I confirm. The problem is urgent.

**Comment by walwoodr** [comment]
Double confirm -- this is a problem for us as well.

**Comment by kartikmalhotra** [comment]
Does someone got the solution to this problem

**Comment by hahaxiaowai** [comment]
I encountered the same problem. I wanted to draw on my mobile phone, but I was stumped by this problem.

**Comment by zafrii** [comment]
I encountered the same problem. When I add draw tool, other layers click event stop working for mobile browsers. However, the click event works fine for desktop browsers.

**Comment by kashalkar** [comment]
+1

**Comment by bren96** [comment]
Running into the same problem, anyone come up with a solution?

**Comment by luisgurmendezMLabs** [comment]
This statement is not correct for mobile devices 
https://github.com/mapbox/mapbox-gl-draw/blob/2b9ce3e58e3695c018a48b6fca78ed1a9d1b67c2/src/events.js#L82

**Comment by hu-bobo** [comment]
I confirm. The problem is urgent !!!

**Comment by scheepers** [comment]
Can confirm. Whenever I draw on the map this error comes up and the draw.create event never fires.

**Comment by kekeshuzhen** [comment]
mapbox-gl: 2.7.0 
Whenever I move the map this log appears, ok, google chrome appears
Has this problem been solved, hurry up

**Comment by deen13** [comment]
+1

**Comment by tibz7** [comment]
+1

**Comment by eirfan** [comment]
18 May 2021, The error is still there. Had to remove the Mapbox Draw and look for other alternative

**Comment by nlintas** [comment]
Problem still here I can confirm too. I am using pop-ups and drawing tools.

**Comment by igorbrandaodev** [comment]
I'm using 'moveend' event and getting this error.

**Comment by erhanask** [comment]
Still this problem exists.

**Comment by PedroVenancio** [comment]
Still an issue here

**Comment by danielsippel** [comment]
I lived with the workaround @zafrii provided on May 28, 2021 quite some time but the error still occurs in the console and causes some further problems. E.g. if a Popup with option {closeOnClick: true} is open - a touch on any other place on the map does not close it.

**Comment by danielsippel** [comment]
As long as my pull request is not merged, you can get rid of the problem by using my fork.

e.g.
`npm install danielsippel/mapbox-gl-draw`

**Comment by danielsippel** [comment]
@chriswhong @mourner 

Can you guys please review my PR (or at least find someone who does) and get this basic map feature, what mapbox-draw is, running on more complex maps for mobile browsers again? Thanks.

**Comment by Usmankt1999** [comment]
@danielsippel I have reviewed you PK , it works pretty well , But i don't know why my project file can not access the theme file from the lib folder , so i manually added that to my project,
Good Job, it do fix that issue but ,

**Comment by danielsippel** [comment]
@Usmankt1999 Thanks for testing. Since my fix has been merged into the main repo, my fork is not necessary any longer.

You can switch back to the main repo: 
`npm install @mapbox/mapbox-gl-draw`

Changelog:
https://github.com/mapbox/mapbox-gl-draw/releases/tag/v1.4.0

**Comment by Usmankt1999** [comment]
@danielsippel  So , we need to re-install the mapbox/mapbox-gl-draw , 

But i thing its fine , i also wanted to customised the theme file so i downloaded it from you repo , 
i think it was work find even if i am using npm install danielsippel/mapbox-gl-draw , Right?

**Comment by danielsippel** [comment]
Works fine, but you will miss future fixes/features, which go to the main repo only.

**Comment by Usmankt1999** [comment]
@danielsippel , Thanks you for your response alright i will use the main repo then :)

**Comment by stepankuzmin** [comment]
Hi all,

I'm reopening this because I'm going to revert the fix https://github.com/mapbox/mapbox-gl-draw/pull/1158 since it currently breaks the touch events as reported in https://github.com/mapbox/mapbox-gl-draw/issues/1154. I missed it during the manual testing, and we'd need to look for a different way to do it. Sorry for the inconvenience.

**Comment by a-hariti** [comment]
Victims++

**Comment by ydrea** [comment]
+1

**Comment by luixo** [comment]
Is there any workaround known at the moment?

**Comment by SorinSu** [comment]
+1

**Comment by LS170** [comment]
+1

**Comment by SamG92** [comment]
+1

**Comment by 2803media** [comment]
I tried this https://github.com/zzarcon/default-passive-events and I still have the error messages but it's working on mobile as expected

**Comment by summerteo** [comment]
Anyone is fixing this issue?

**Comment by luixo** [comment]
So I tested out a version with `preventDefault` calls removed, it works all right on both desktop and mobile though I didn't make proper testing.
I published a [patch](https://gist.github.com/luixo/28421e046de247e4ebaed28e31f50af8) for version 1.4.2, use it with [regular](https://github.com/ds300/patch-package#applying-patches) `patch-package` flow.

**Comment by virux99** [comment]
+1

**Comment by Archetylator** [comment]
This bug still appears in v1.4.1

**Comment by Archetylator** [comment]
I created a PR which resolves that issue I think. I removed preventDefault() on touchstart and touchmove events, but left it inside touchend event. Seems to work without problems on mobile and desktop versions.

**Comment by TyLippe** [comment]
> I created a PR which resolves that issue I think. I removed preventDefault() on touchstart and touchmove events, but left it inside touchend event. Seems to work without problems on mobile and desktop versions.

Hey there! Are we able to get this PR merged in soon? Currently running into this issue and hoping for this fix to come through. Thanks!

**Comment by ClinMyk2018** [comment]
Dropping this here:

`this.map.on('touchstart', () => { event.preventDefault = Function.prototype });` 

> _(this.map = **your map instance**)_

After creating the draw feature and adding it as a control to the map, throw that line in.

**Comment by abelfrias** [comment]
> Dropping this here:
> 
> `this.map.on('touchstart', () => { event.preventDefault = Function.prototype });`
> 
> > _(this.map = **your map instance**)_
> 
> After creating the draw feature and adding it as a control to the map, throw that line in.

Not working for me :man_shrugging: 
And I guess you meant `this.map.on('touchstart', (event) => { event.preventDefault = Function.prototype });`, you missed the 'event' argument for the callback function.

**Comment by brinsleylogic** [comment]
+1 for this still being an issue on v1.4.2. Anyone @ mapbox even watching this?

**Comment by stepankuzmin** [comment]
Hi everyone. I've merged the [fix](https://github.com/mapbox/mapbox-gl-draw/pull/1195) from @Archetylator that resolves this issue. This is now published as `@mapbox/mapbox-gl-draw@v1.4.3` https://github.com/mapbox/mapbox-gl-draw/releases/tag/v1.4.3

Please try it out and comment if this resolves the issue.

**Comment by abelfrias** [comment]
Thank you @Archetylator @stepankuzmin, it looks like it is working fine for now! Errors do not appear in the console and behaviour is as expected. I only tested it in the DevTools Device Simulation and no issues so far. Let's see if we got rid of this issue at last!

**Comment by ludoviccumin** [comment]
Hi, I still have this problem on the map's children but not on the Markers anymore.
Here is an example : 
`map.on('touchstart', 'unclustered-point', (e) => {
         const card = document.createElement('div');
         card.innerHTML = content;
         map.getCanvasContainer().appendChild(card);
});`
If "content" contains a link, this link doesn't work on mobile devices.

**Comment by abelfrias** [comment]
I am coming back because it looks like the solution hid the annoying console error messages, but the issue looks deeper than that.

**Context**
I have a Vector Tile layer loaded, and I interact with it with some listeners in the map. Basically, in non-touchscreen devices I added some `mouseover` and `mouseout` listeners to create a hover effect, and then for all devices I have a `click` event listener to manage the 'selection' of boundaries.

**Issue**
When I add the Draw Control to the map, touchscreen devices are not able to 'select' the boundaries anymore (i.e., `click` event listener is doing nothing). However, in non-touchscreen devices it works as expected.

Before the recently merged fix, every time a user tried to select a boundary while Draw Control was mounted, the `Unable to preventDefault inside passive event listener invocation` error appeared in the console. Now, nothing happens at all: nor an error appears, nor the boundary is selected.
